---
- hosts: glusterfs
  tasks:
    - name: allow connection
      command: "{{ item }}"
      with_items:
        - firewall-cmd --zone=public --add-port=49152/tcp --permanent
        - firewall-cmd --zone=public --add-port=24007-24008/tcp --permanent
    - name: restart firewall
      service:
        name: firewalld
        state: restarted
