---
<<<<<<< HEAD
- name: install glusterfs38 
  yum: name="centos-release-gluster38" update_cache="yes" state="latest" 
=======
- name: install glusterfs38
  yum: name="centos-release-gluster38" update_cache="yes" state="latest"
>>>>>>> 30e6fd5e8abbec29e8ff4cef0af3349429f317e9

- name: install glusterfs
  yum:
    name: 
      - glusterfs
      - glusterfs-libs
      - glusterfs-server
    update_cache: yes
    state: latest

- name: start glusterfs
  systemd:
    name: glusterd
    state: started
    enabled: true

- name: allow connection
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --add-port=49152/tcp --permanent
    - firewall-cmd --zone=public --add-port=24007-24008/tcp --permanent

- name: restart firewall
  service:
    name: firewalld
    state: restarted

